- name: Install common packages
  become: yes
  package:
    name:
      - tig
      - autojump
      - vim
      - bat
      - jq
      - yq
      - git
      - git-delta
      - m4
      - unzip
      - silversearcher-ag
      - fzf
      - coreutils
      - ca-certificates
      - apt-transport-https
      - jsonnet

# kubectl
- name: Install kubectl
  become: yes
  community.general.snap:
    name: kubectl
    classic: true

# Vault
- name: Check hashicorp repo is present
  stat: 
    path: /etc/apt/sources.list.d/hashicorp.list
  register: hashicorp_repo

- name: Install hashicorp repository
  shell: |
    wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  when: not hashicorp_repo.stat.exists

- name: Install hashicorp vault
  become: yes
  apt:
    update-cache: true
    name: vault

# Docker
- name: Install docker
  include_tasks: docker.yml

# Helm
- name: Check helm repo is present
  stat: 
    path: /etc/apt/sources.list.d/helm-stable-debian.list
  register: helm_repo

- name: Install helm repository
  shell: |
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  when: not helm_repo.stat.exists

- name: Install helm
  become: yes
  apt:
    update-cache: true
    name: helm

# Install tools with different package
# for different arch. inludes k9s, awscli, helmfile etc.
- name: Install arch specific packages
  include_tasks: multi-arch.yml

# Configure Utilities
- name: Configure utilities
  include_tasks: configure.yml